name: 自动打包发布
on:
  push:
    branch: [main]
jobs:
  build-dist:
    name: 构建 chrome 扩展程序安装包
    runs-on: ubuntu-latest
    steps:
      # 准备源码
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 安装yarn 环境
        uses: borales/actions-yarn@v2.3.0
      - run: yarn add
      - run: yarn build

      - name: 上传共享的数据
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  release:
    name: 发布版本
    runs-on: ubuntu-latest
    needs: build-dist
    steps:
      - name: 下载共享数据
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: 压缩文件
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: lan.zip
          exclusions: "*.git* /*node_modules/* .editorconfig"

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}v${{ github.run_number }}
          release_name: Release ${{ github.ref }}v${{ github.run_number }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lan.zip
          asset_name: lan_v${{ github.run_number }}.zip
          asset_content_type: application/zip
